name = "logto-oauth-profile-mapper"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-06-10"
workers_dev = true
minify = true

[vars]
CORS = "https://id.mxs.app"
ROOT = "https://logto-oauth-profile-mapper.t2v.workers.dev"

[placement]
mode = "smart"
